package com.foxya.coin.notification.enums;

public enum NotificationType {
    DEPOSIT_SUCCESS,
    DEPOSIT_FAILED,
    WITHDRAW_SUCCESS,
    WITHDRAW_FAILED,
    EXCHANGE_SUCCESS,
    EXCHANGE_FAILED,
    SWAP_SUCCESS,
    SWAP_FAILED,
    NOTICE,
    INQUIRY_SUCCESS,
    INQUIRY_ANSWERED,
    MINING_LIMIT_REACHED,
    MINING_SESSION_ENDED,
    LEVEL_UP,
    MISSION_ACTIVATED,
    MISSION_COMPLETED,
    AIRDROP_RECEIVED,
    AIRDROP_UNLOCKED,
    TEAM_MEMBER_JOINED,
    NEW_DEVICE_LOGIN
}

